name: vokativ
description: A vokativ library for Dart language. Can take (fe)male Czech name and return its declension. Can also determine gender based on Czech name.
version: 1.1.0
repository: https://github.com/SedlarDavid/vokativ
issue_tracker: https://github.com/SedlarDavid/vokativ/issues
topics:
  - czech
  - vokativ
  - declension
  - names
  - gender

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.0
