name: vokativ
description: A vokativ library for Dart language.
version: 1.0.0
repository: https://github.com/SedlarDavid/vokativda

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


