name: vokativ
description: A vokativ library for Dart language. Can take (fe)male Czech name and return its declension. Can also determine gender based on czech name.
version: 1.0.3
repository: https://github.com/SedlarDavid/vokativ

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.4

